### ISSUE TITLE
Missing unit skill description and HTML leftovers

### ISSUE THREAD

**Issue by lmachens** [lmachens/soc.gg#12]
Some units have HTML like `<span class="positive">+1</span> Attacks` (https://www.soc.gg/en/units/Arleon/FaeySpirit). This is alread converted on other pages like the stats.
Other units have missing skill descriptions like Helpless on https://www.soc.gg/units/Barya/Hellbreath

**Comment by 0x0014** [comment]
Is this up for grabs? I'd like to tackle this one if no one else is working on it?

**Comment by lmachens** [comment]
Sure, go for it 👍
https://github.com/lmachens/soc.gg/blob/main/pages/wielders/[type].tsx#L103
This might be helpful to solve this issue.

**Comment by 0x0014** [comment]
I have the code ready to correct the HTML output issue, but looking at the json files for data mapping we're missing 
 description entries for inspiring, helpless, etc. I can see others that populate have full entries under "Bacterias/{unit_skill}/Description". Looking at the readme the data extraction is part of a different repo. Correct me if I'm wrong, but I'm not sure I can address that particular issue with what is available in this current repo?

![correct_html_output](https://user-images.githubusercontent.com/13407547/171988737-a41554fc-207c-42c6-ab24-3afdbf86ca67.png)

**Comment by lmachens** [comment]
The extractor is not part of an additional repository anymore, I forgot to remove the note.
See extractor subfolder.
But I think it's not required to change it.

The termMap.json includes all terms used in-game. Maybe the identifier is different for these skills.

I would search in that file for the correct term. Another option is to investigate the extractor files and see how Songs of Conquest read the description.

**Comment by 0x0014** [comment]
@lmachens I'm not familiar with the extractor. So I'm going to go over what I've looked into and perhaps you can point me to something I'm missing regarding the missing definitions?

I doubled checked the identifiers and they are correct. For example, 'Helpless' has as ID of 61. So that's not the issue as far as I can tell

I re-ran the steps to generate the json files & values from the repo. But running a grep against it we still only have the single match for the traits that have no description. So I started digging into the game files to see if I could figure out where those values are coming from and where the extractor is going wrong

Using 'Helpless' as an example, we get a few hits when running a grep against the code base. Ones of interest to me were the I2Languages.asset files, and the BacteriaTypes.cs, which confirmed the trait ID value. When checking the I2Languages file we see the single entry there, whereas others, like Reload, have the initial entry and then a second description entry immediately after the initial Bacterias entry

Based off what I'm seeing in the .asset files what we have in the termMap.json file is _correct_. Is there something I am missing?
